language: clojure
jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

script: lein uberjar

after_success:
  - CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

notifications:
  email:
    on_failure: change
