language: clojure
jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'CREATE DATABASE essentials;' -U postgres

script:
  - lein uberjar
  - CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov

after_success:
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

notifications:
  email:
    on_failure: change
